version: "3.0"

services:
  shell:
    build: .
    image: miadocker/ready-for-rails5
    command: bash
    volumes:
      - .:/app
      # - ./gems:/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems

  web:
    image: miadocker/ready-for-rails5
    command: bash
    volumes:
      - .:/app
